export const defaultStyles = [
  {
    name: "Default",
    borderRadius: "12px",
    borderColor: "#e5e7eb",
    backgroundColor: "#ffffff",
    textColor: "#111827",
    accentColor: "#3b82f6",
    showImage: true,
    showFavicon: true,
    layout: "horizontal",
    id: 1,
  },
  {
    name: "Dark",
    borderRadius: "8px",
    borderColor: "#374151",
    backgroundColor: "#1f2937",
    textColor: "#f9fafb",
    accentColor: "#60a5fa",
    showImage: true,
    showFavicon: true,
    layout: "horizontal",
    id: 2,
  },
  {
    name: "Minimal",
    borderRadius: "4px",
    borderColor: "#d1d5db",
    backgroundColor: "#ffffff",
    textColor: "#374151",
    accentColor: "#6b7280",
    showImage: false,
    showFavicon: true,
    layout: "compact",
    id: 3,
  },
  {
    name: "Card",
    borderRadius: "16px",
    borderColor: "#e5e7eb",
    backgroundColor: "#f9fafb",
    textColor: "#111827",
    accentColor: "#10b981",
    showImage: true,
    showFavicon: true,
    layout: "vertical",
    id: 4,
  },
];
